import type { Metadata } from "next";
import localFont from "next/font/local";
import { Baloo_Paaji_2 } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "./logo.png";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// const baloo = Baloo_Paaji_2({ weight: "800", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function ProfileAvatar() {
  return (
    <Avatar>
      <AvatarFallback>JD</AvatarFallback>
    </Avatar>
  );
}

function Taskbar() {
  return (
    <div
      style={{
        width: "100%",
        height: "70px",
        backgroundColor: "black",
        position: "fixed",
        display: "flex",
        alignItems: "center",
      }}
    >
      <ul
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          listStyle: "none",
          padding: 0,
          marginLeft: "15px",
          marginRight: "15px",
          width: "100%",
        }}
      >
        <li>
          <Image src={logo} alt="logo" width={50} height={50} />
        </li>
        <li>
          <ProfileAvatar />
        </li>
      </ul>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Taskbar />
        {children}
      </body>
    </html>
  );
}
